### ISSUE TITLE
python face_verify.py error

### ISSUE THREAD

**Issue by bianxg** [TreB1eN/InsightFace_Pytorch#140]
I don't train and just want to test.  Where can I download model_final.pth? Thanks

Traceback (most recent call last):
  File "face_verify.py", line 32, in <module>
    learner.load_state(conf, 'final.pth', False, True)
  File "D:\10working\30project\face\insideface\InsightFace_Pytorch\Learner.py", line 82, in load_state
    self.model.load_state_dict(torch.load(save_path/'model_{}'.format(fixed_str)))
  File "D:\program\pytorch_insightface\lib\site-packages\torch\serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\program\pytorch_insightface\lib\site-packages\torch\serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\program\pytorch_insightface\lib\site-packages\torch\serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
TypeError: invalid file: WindowsPath('work_space/models/model_final.pth')

**Comment by venkata-srinivasan** [comment]
Did you get it fixed?

**Comment by charmere** [comment]
Just add the absolute path.it is ok for me.

**Comment by aalekseyantonov** [comment]
I used the [file](https://pan.baidu.com/s/12BUjjwy1uUTEF9HCx5qvoQ) and renamed it with "model_final.pth"

You can use another pretrained model instead this one
