### ISSUE TITLE
No such file or directory: 'data/facebank/facebank.pth'--->RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by WW2401** [TreB1eN/InsightFace_Pytorch#160]
@TreB1eN  Hi, when I met the error No such file or directory: 'data/facebank/facebank.pth', I ran python face_verify.py --update, but I met another problem as follows. Do you know the reason? Thanks.
Environment is as requirement shown,
cuda:V10.0.130
**I  changed cuda10 to cuda9, the problem still exsits.**

ir_se_50 model generated
learner loaded
Traceback (most recent call last):
File "face_verify.py", line 36, in
targets, names = prepare_facebank(conf, learner.model, mtcnn, tta = args.tta)
File "/home/InsightFace_Pytorch/utils.py", line 49, in prepare_facebank
img = mtcnn.align(img)
File "/home/InsightFace_Pytorch/mtcnn.py", line 23, in align
_, landmarks = self.detect_faces(img)
File "/home/InsightFace_Pytorch/mtcnn.py", line 85, in detect_faces
boxes = run_first_stage(image, self.pnet, scale=s, threshold=thresholds[0])
File "/home/InsightFace_Pytorch/mtcnn_pytorch/src/first_stage.py", line 35, in run_first_stage
output = net(img)
File "/home/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in call
result = self.forward(*input, **kwargs)
File "/home/InsightFace_Pytorch/mtcnn_pytorch/src/get_nets.py", line 67, in forward
x = self.features(x)
File "/home/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in call
result = self.forward(*input, **kwargs)
File "/home/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
input = module(input)
File "/home/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in call
result = self.forward(*input, **kwargs)
File "/home/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

**Does anyone know the reason? T_T**

**Comment by WW2401** [comment]
Does anyone know the reason?
